import { Project } from "@/types/project";

export const projects: Project[] = [
  {
    id: "01",
    slug: "haus-of-taste",
    title: "HAUS OF TASTE",
    category: "UX/UI Design",
    bgText: "Haus Of Taste",
    bgColor: "#151b22",
    imgLeftTilted: true,
    titleImage: "/mockups/hot-logo.png",
    customBg: "/mockups/hot-bg.png",
    centerImage: "/mockups/hot-iphone.png",
    layout: "case-study",
    details: {
      role: "Lead UX/UI Designer",
      tools: ["Figma", "Adobe CC", "Framer"],
      year: "2024",
      platforms: ["iOS", "Android"],
    },
  },
  {
    id: "02",
    slug: "green-butcher",
    title: "GREEN BUTCHER",
    category: "Brand Design",
    bgText: "GREEN",
    bgColor: "#1f2a1e",
    imgLeftTilted: false,
    layout: "hero",
  },
  {
    id: "03",
    slug: "the-experience",
    title: "THE EXPERIENCE",
    category: "UX/UI Design",
    bgText: "USER EXP",
    bgColor: "#0a0a0a",
    imgLeftTilted: true,
    layout: "hero",
  },
  {
    id: "04",
    slug: "iconic-interiors",
    title: "ICONIC INTERIORS",
    category: "Brand Design",
    bgText: "JOSEPH",
    bgColor: "#eaaa00",
    imgLeftTilted: false,
    layout: "hero",
  },
];
