import { Project } from "@/types/project";
import { p } from "@/lib/base-path";

export const projects: Project[] = [
  {
    id: "01",
    slug: "haus-of-taste",
    title: "HAUS OF TASTE",
    category: "UX/UI Design",
    bgText: "Haus Of Taste",
    bgColor: "#151b22",
    imgLeftTilted: true,
    titleImage: p("/mockups/hot-logo.png"),
    customBg: p("/mockups/hot-bg.png"),
    centerImage: p("/mockups/hot-iphone.png"),
    layout: "case-study",
    details: {
      role: "Lead UX/UI Designer",
      tools: ["Figma", "Adobe CC", "Framer"],
      year: "2024",
      platforms: ["iOS", "Android"],
    },
  },
  {
    id: "05",
    slug: "bitsync",
    title: "BITSYNC",
    category: "UX/UI Design",
    bgText: "Bitsync",
    bgColor: "#0a0c10",
    imgLeftTilted: false,
    titleImage: p("/mockups/bitsync/logo.png"),
    customBg: p("/mockups/bitsync/bg.png"),
    centerImage: p("/mockups/bitsync/mockup.png"),
    layout: "case-study",
    titlePosition: "bottom",
    details: {
      role: "UX/UI Designer",
      tools: ["Figma", "Adobe Illustrator"],
      year: "2024",
      platforms: ["iOS", "Web"],
    },
  },
  {
    id: "02",
    slug: "green-butcher",
    title: "GREEN BUTCHER",
    category: "Brand Design",
    bgText: "GREEN",
    bgColor: "#1f2a1e",
    imgLeftTilted: false,
    layout: "hero",
  },
  {
    id: "03",
    slug: "the-experience",
    title: "THE EXPERIENCE",
    category: "UX/UI Design",
    bgText: "USER EXP",
    bgColor: "#0a0a0a",
    imgLeftTilted: true,
    layout: "hero",
  },
  {
    id: "04",
    slug: "iconic-interiors",
    title: "ICONIC INTERIORS",
    category: "Brand Design",
    bgText: "JOSEPH",
    bgColor: "#eaaa00",
    imgLeftTilted: false,
    layout: "hero",
  },
];

