import { Project } from "@/types/project";
import { p } from "@/lib/base-path";

export const projects: Project[] = [
  {
    id: "01",
    slug: "haus-of-taste",
    title: "HAUS OF TASTE",
    category: "UX/UI Design",
    bgText: "Haus Of Taste",
    bgColor: "#151b22",
    imgLeftTilted: true,
    titleImage: p("/mockups/hot-logo.png"),
    customBg: p("/mockups/hot-bg.png"),
    centerImage: p("/mockups/hot-iphone.png"),
    layout: "case-study",
    details: {
      role: "Lead UX/UI Designer",
      tools: ["Figma", "Adobe CC", "Framer"],
      year: "2024",
      platforms: ["iOS", "Android"],
    },
  },
  {
    id: "03",
    slug: "one-piece",
    title: "ONE PIECE X ADIDAS",
    category: "UX/UI Design",
    bgText: "ONE PIECE",
    bgColor: "#e21e26",
    imgLeftTilted: true,
    titleImage: p("/images/one-piece/One piece logo.png"),
    secondaryImage: p("/images/one-piece/adidas logo.png"),
    customBg: p("/images/one-piece/Background.png"),
    centerImage: p("/images/one-piece/Free_Iphone_14_Pro_Mockup_3b.png"),
    layout: "case-study",
    details: {
      role: "UX/UI Designer",
      tools: ["Figma", "Adobe CC"],
      year: "2024",
      platforms: ["Mobile", "E-commerce"],
    },
  },
  {
    id: "05",
    slug: "bitsync",
    title: "BITSYNC",
    category: "UX/UI Design",
    bgText: "Bitsync",
    bgColor: "#0a0c10",
    imgLeftTilted: false,
    titleImage: p("/mockups/bitsync/logo.png"),
    customBg: p("/mockups/bitsync/bg.png"),
    centerImage: p("/mockups/bitsync/mockup.png"),
    layout: "case-study",
    titlePosition: "bottom",
    details: {
      role: "UX/UI Designer",
      tools: ["Figma", "Adobe Illustrator"],
      year: "2024",
      platforms: ["iOS", "Web"],
    },
  },
  {
    id: "06",
    slug: "shell",
    title: "SHELL",
    category: "Brand Design",
    bgText: "Shell",
    bgColor: "#FFD500",
    imgLeftTilted: false,
    titleImage: p("/images/shell/Title.png"),
    customBg: p("/images/shell/Background.png"),
    centerImage: p("/images/shell/Bmw.png"),
    layout: "case-study",
    details: {
      role: "Lead Multimedia Designer",
      tools: ["Figma", "Adobe CC"],
      year: "2024",
      platforms: ["iOS", "Android"],
    },
  },
  {
    id: "04",
    slug: "essops",
    title: "ESSOPS",
    category: "Brand Design",
    bgText: "Essops",
    bgColor: "#EBEBEB",
    imgLeftTilted: false,
    titleImage: p("/images/essops/Essops logo.png"),
    customBg: p("/images/essops/Background.png"),
    centerImage: p("/images/essops/Furniture.png"),
    layout: "case-study",
    details: {
      role: "Lead Multimedia Designer",
      tools: ["Figma", "Adobe CC"],
      year: "2024",
      platforms: ["Web", "Print"],
    },
  },
  {
    id: "07",
    slug: "hi-q",
    title: "HI-Q",
    category: "Brand Design",
    bgText: "Hi-Q",
    bgColor: "#005696",
    imgLeftTilted: false,
    titleImage: p("/images/hi-q/hi-q-logo.png"),
    secondaryImage: p("/images/hi-q/shortyslogo 1.png"),
    customBg: p("/images/hi-q/background.png"),
    centerImage: p("/images/hi-q/wheels 1.png"),
    layout: "case-study",
    details: {
      role: "Multimedia Designer",
      tools: ["Adobe CC", "Photography"],
      year: "2024",
      platforms: ["Print", "Digital"],
    },
  },
  {
    id: "08",
    slug: "bubbles",
    title: "BUBBLES",
    category: "Brand Design",
    bgText: "Bubbles",
    bgColor: "#FFFFFF",
    imgLeftTilted: false,
    titleImage: p("/images/bubbles/Bubbles logo.png"),
    secondaryImage: p("/images/bubbles/Title.png"),
    customBg: p("/images/bubbles/Background.png"),
    layout: "case-study",
    details: {
      role: "Brand Identity Designer",
      tools: ["Adobe Illustrator", "Photoshop"],
      year: "2024",
      platforms: ["Packaging", "Web"],
    },
  },
  {
    id: "09",
    slug: "the-joint",
    title: "THE JOINT",
    category: "Web Design",
    bgText: "The Joint",
    bgColor: "#050505",
    imgLeftTilted: false,
    titleImage: p("/images/the-joint/Header.png"),
    customBg: p("/images/the-joint/Background.png"),
    centerImage: p("/images/the-joint/Title.png"),
    layout: "case-study",
    details: {
      role: "Web Designer",
      tools: ["Figma", "Webflow"],
      year: "2024",
      platforms: ["Web"],
    },
  },
  {
    id: "10",
    slug: "burger-restaurant",
    title: "BURGER RESTAURANT",
    category: "Web Design",
    bgText: "Burger",
    bgColor: "#050505",
    imgLeftTilted: false,
    titleImage: p("/images/burger-restaurant/Title.png"),
    customBg: p("/images/burger-restaurant/Background.png"),
    layout: "case-study",
    details: {
      role: "Web Designer",
      tools: ["Figma"],
      year: "2024",
      platforms: ["Web"],
    },
  },
  {
    id: "11",
    slug: "restaurant",
    title: "RESTAURANT",
    category: "Web Design",
    bgText: "Taste",
    bgColor: "#ffffff",
    imgLeftTilted: false,
    titleImage: p("/images/restaurant/Title.png"),
    customBg: p("/images/restaurant/Background.png"),
    layout: "case-study",
    details: {
      role: "Web Designer",
      tools: ["Figma"],
      year: "2024",
      platforms: ["Web"],
    },
  },
];
